export const projects = [
    {
        slug: 'oraanj-interior-design',
        name: 'Oraanj Interior Design',
        role: 'Web Developer',
        dates: 'April 2023 - June 2023',
        type: 'Freelance',
        visitUrl: '#',
        techStack: ['HTML5', 'CSS3', 'Bootstrap 5', 'JavaScript', 'PHP', 'jQuery'],
        tasks: ['Web Development', 'Accessibility', 'Performance Optimization'],
        description: 'Interior design platform frontend built for Multigraphics Group. Raised accessibility score to 97/100 through semantic HTML restructuring and performance optimization, including lazy-loading and reduced layout shifts. Delivered a fully responsive mobile-first redesign, converting static Figma designs to production-ready code, cutting client-reported UI bugs by 40% through cross-browser testing.',
        visuals: [
            { type: 'image', label: 'Slide 1 • Image' },
            { type: 'image', label: 'Slide 2 • Image' },
        ],
    },
    {
        slug: 'holyherbs',
        name: 'HolyHerbs',
        role: 'Frontend Developer',
        dates: '2023 - 2024',
        type: 'Freelance',
        visitUrl: '#',
        techStack: ['WordPress', 'Razorpay'],
        tasks: ['Frontend Development', 'E-commerce Integration'],
        description: 'Ecommerce site built on WordPress with Razorpay payment integration for a freelance client.',
        visuals: [
            { type: 'image', label: 'Slide 1 • Image' },
        ],
    },
    {
        slug: 'lume-studio',
        name: 'Lume Studio',
        role: 'Frontend Developer',
        dates: '',
        type: 'Personal',
        visitUrl: '#',
        techStack: ['React', 'Vite', 'TypeScript', 'Puter', 'Claude API', 'Gemini API', 'Modern UI Architecture'],
        tasks: ['Frontend Development', 'AI Integration'],
        description: 'An AI platform where users upload 2D floor plans and it transforms them into photorealistic 3D renders using advanced AI models. Built with a modern UI architecture, Puter for serverless workers and KV storage, and persistent cloud hosting.',
        visuals: [
            { type: 'image', label: 'Slide 1 • Image' },
        ],
    },
    {
        slug: 'inkwell',
        name: 'Inkwell',
        role: 'Frontend Developer',
        dates: '',
        type: 'Personal',
        visitUrl: '#',
        techStack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Clerk', 'Vapi AI', 'Vercel Blob', 'MongoDB'],
        tasks: ['Frontend Development', 'AI Integration', 'Full Stack Development'],
        description: 'An AI voice-based PDF conversation platform, reducing document review time by 70% per session. Integrated Vapi AI for real-time voice interaction and Vercel Blob for scalable file storage. Resolved 5+ critical deployment blockers, including Turbopack/Webpack conflicts, pdfjs-dist v5 incompatibility, and Clerk auth redirect loops.',
        visuals: [
            { type: 'image', label: 'Slide 1 • Image' },
        ],
    },
    {
        slug: 'ai-resume-analyzer',
        name: 'AI Resume Analyzer',
        role: 'Frontend Developer',
        dates: '',
        type: 'Personal',
        visitUrl: '#',
        techStack: ['React', 'Vite', 'Puter.js', 'Zustand', 'TypeScript', 'Tailwind CSS', 'React Router v7'],
        tasks: ['Frontend Development', 'AI Integration'],
        description: 'A tool reducing resume review time to under 15 seconds by integrating Puter.js for file handling and AI-driven feedback, built with a modular type-safe architecture. Used Zustand for lightweight global state management, keeping bundle size minimal and improving overall app performance.',
        visuals: [
            { type: 'image', label: 'Slide 1 • Image' },
        ],
    },
    {
        slug: 'lynk',
        name: 'Lynk',
        role: 'Frontend Developer',
        dates: '',
        type: 'Personal',
        visitUrl: '#',
        techStack: ['React', 'Node.js', 'MongoDB', 'TanStack Query'],
        tasks: ['Full Stack Development'],
        description: 'A full-stack URL shortener with custom link generation and a JWT/Bcrypt authentication system for secure, protected user accounts. Reduced redundant network requests by 35% using TanStack Query for server state caching, improving perceived load time across all devices.',
        visuals: [
            { type: 'image', label: 'Slide 1 • Image' },
        ],
    },
    {
        slug: 'iphone-clone',
        name: 'iPhone Clone',
        role: 'Frontend Developer',
        dates: '',
        type: 'Personal',
        visitUrl: '#',
        techStack: ['React', 'Vite', 'Tailwind CSS', 'Three.js', 'GSAP', 'JavaScript'],
        tasks: ['Frontend Development', '3D Development'],
        description: 'A personal recreation of the iPhone marketing site, exploring 3D web development with Three.js alongside React and GSAP for animation.',
        visuals: [
            { type: 'image', label: 'Slide 1 • Image' },
        ],
    },
];

export const getProjectBySlug = (slug) => projects.find((p) => p.slug === slug);